### ISSUE TITLE
TESTYONLINE- 010 - panel logowania 

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#11]
Przygotować panel strony, z formularzem rejestracji i logowania do panelu użytkownika zgodnie z szablonem.

**Comment by wlAristo** [comment]
Wersja 1.0 naszej strony została stworzona. Zawiera ona panel logowania, panel rejestracji, widok zalogowanego użytkownika oraz możliwość wylogowania. 

Dostęp pod następującym adresem:
http://doublem.nazwa.pl/testy_online/

**Comment by JanStas** [comment]
Przetestowałem działa poprawnie. 

Przeprowadzić testy. @oskrz  @murtagh669

**Comment by murtagh669** [comment]
Zgadam sie, testy nie wykazały błędów.
