### ISSUE TITLE
TESTYONLINE- 011 Przygotować layout do strony logowania 

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#12]
Przygotować layout do logowania i rejestracji, będący zarazem stroną startową. 
Schemat strony w repo.
#11

**Comment by wlAristo** [comment]
Proponowany okodowany Layout na podstawie wytycznych od @swagistic został wdrożony dla strony wejściowej tj. rejestracji. Styl stworzony dla rozdzielczości ekranu nie mniejszej niż 1024px. W przypadku zatwierdzenia, styl zostanie rozszerzony o wersje mobilne.

**Comment by wlAristo** [comment]
Layout strony logowania został wdrożony.
