### ISSUE TITLE
TESTYONLINE- 013 Panel użytkowika

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#14]
Przygotować panel użytkownika zgodnie z wymogami zawartymi w szkicu strony.

https://github.com/JanStas/TestyOnline/blob/master/SzkicStrony.png

**Comment by wlAristo** [comment]
Wstępna wersja panelu użytkownika została stworzona. Strona, na którą zostaje przeniesiony użytkownik po uzyskaniu dostępu do systemu została zakodowana. Przyciski przenoszące do funkcjonalności, które jeszcze nie zostały wdrożone do systemu również zostały zaprojektowane.
