### ISSUE TITLE
TESTYONLINE- 015 Panel logowania

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#16]
Wykonać testy rejestracji i logowania wraz ze sporządzeniem raportu.
Umiescić raport w nowym branchu Protokoły

_Przykładowy raport_
https://github.com/JanStas/TestyOnline/blob/Testy/08_upedu_plan_testow%2020.10.08.pdf

**Comment by JanStas** [comment]
Zmienić szatę na stronie logowania.

**Comment by swagistic** [comment]
Testy wykonałem. Załączam raport.
[testy_001.pdf](https://github.com/JanStas/TestyOnline/files/204657/testy_001.pdf)

**Comment by JanStas** [comment]
PRoszę o wgranie pliku z protokołem testów w formacie *.doc

**Comment by JanStas** [comment]
Ponawiam prośbę @swagistic

**Comment by swagistic** [comment]
Plik został wgrany zgodnie z oczekiwaniami.

[testy_001.docx](https://github.com/JanStas/TestyOnline/files/213653/testy_001.docx)
