### ISSUE TITLE
TESTYONLINE- 021 Panel administratora

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#22]
Przygotować panel użytkownika zgodnie z wymogami zawartymi w szkicu strony.

https://github.com/JanStas/TestyOnline/blob/master/SzkicStrony.png

**Comment by wlAristo** [comment]
Panel logowania do panelu administratora został okodowany. Dostęp pod $baseSiteUrl/admin/

**Comment by wlAristo** [comment]
Dane dostępowe do panelu administratora

Login: admin
Hasło: admin

**Comment by wlAristo** [comment]
Została zaimplementowana funkcjonalność tworzenia nowej grupy. 
Dostęp pod $baseSiteUrl/admin/dodaj_nowa_grupe

Wymagane uwierzytelnienie.

**Comment by wlAristo** [comment]
Została stworzona funkcjonalność wyświetlająca w postaci tabeli utworzone grupy. Na tą chwilę funkcjonalności są tworzone bez elementów graficznych stąd czytelność może być gorsza. Metoda podliczająca ilość przypisanych użytkowników do grupy została utworzona.

**Comment by wlAristo** [comment]
Została zaimplementowana funkcjonalność odpowiadająca za możliwość usuwania wybranej grupy. 

Dostęp: $baseSiteUrl/admin/grupy/

**Comment by JanStas** [comment]
Przyjąłem
