### ISSUE TITLE
TESTYONLINE- 022 Opracować grafikę na stronę logowania

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#23]

**Comment by JanStas** [comment]
https://github.com/JanStas/TestyOnline/blob/master/Loowanie_SzataGraficzna_2.1.png

Proszę o opinię i wypowiedź na temat tej szaty graficznej. 
Główne cechy:
- prosta
- lekka dla oka
- zrównoważona kolorystycznie

**Comment by murtagh669** [comment]
Moja opinia:

1.Jasne kolory wieczorami mogą lekko drażnić oczy
2. Brakuje mi czegoś w lewej dolnej sekcji. Może ten panel logowania dałbyś trochę większy?

**Comment by oskrz** [comment]
Brakuje:
 mała 'chmurka' po krótce opisująca oferte naszej strony, albo chociaż do czego to służy.

**Comment by wlAristo** [comment]
Sugeruję umieszczenie jakiegoś sloganu w dolnej-lewej części strony w celu wykorzystania miejsca. 
Czy ktoś ma propozycję tekstu na slogan?

**Comment by swagistic** [comment]
Wygląd prezentuje się nowocześnie i pasuje pod panujące obecnie trendy. 
Prosta grafika  jak dla mnie jest czytelna i przyjazna dla oka.
Kolory dobrze się prezentują oraz są składnie dobrane. 
Całość jest spójna i wpada w pamięć

**Comment by murtagh669** [comment]
@wlAristo  "I wszystko staje się prostsze!"
