### ISSUE TITLE
TESTYONLINE- 023 Przygotowanie szaty graficznej panelu użytkownika

### ISSUE THREAD

**Issue by murtagh669** [JanStas/TestyOnline#24]
@JanStas 

Proszę o przygotowanie szaty graficznej panelu użytkownika

**Comment by JanStas** [comment]
Załączam projekt. 

https://github.com/JanStas/TestyOnline/blob/Grafiki/LayoutPanelUzytkownika.png

**Comment by murtagh669** [comment]
Dla mnie jest OK.

**Comment by oskrz** [comment]
Super, brak zastrzeżeń
