### ISSUE TITLE
TESTYONLINE- 026 Testy panel administracyjny

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#29]
Przeprowadzić test panelu administracyjnego sporządzić protokół

**Comment by oskrz** [comment]
Raport sporządzony, czekam na potwierdzenie

**Comment by murtagh669** [comment]
Raport jest do poprawy. Proszę o rozpisanie bardziej szczegółowo przeprowadzonych testów. Proszę umieścić plik w formacie PDF

**Comment by oskrz** [comment]
Poprawiłem raport
