### ISSUE TITLE
TESTYONLINE -032 Testy 001

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#36]
Proszę o wykonanie testów:
- logowania
- rejstracji
- wylogowania
- podgląd panelu użytkownika
- graficzne przedstawienie zgodnie z szablonem

**Comment by oskrz** [comment]
Done

**Comment by JanStas** [comment]
Raport jest do poprawy. Proszę o rozpisanie bardziej szczegółowo przeprowadzonych testów. Proszę umieścić plik w formacie PDF

**Comment by oskrz** [comment]
Poprawione

**Comment by JanStas** [comment]
Przyjąłem
