### ISSUE TITLE
TESTYONLINE -033 Panel użytkownika

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#38]
Należy nanieść następujące poprawki:
- Dodaj stopkę w panelu użytkownika oraz uiścić dodatkowe informacje
  Testy Online - Projekt Zespołowy 2016 Wszelkie prawa zastrzeżone </br>
  <a href="#"> Regulamin korzystania z serwisu<a>
- Wyróżnić nagłówek tabeli, proponuje kolor nagłówka #2186be,  czcionka #FFF  pogrubiona

**Comment by swagistic** [comment]
Zadania zostały zrealizowane dokładnie według zaleceń.
