### ISSUE TITLE
TESTYONLINE -035 Tworzenie Modelu

### ISSUE THREAD

**Issue by murtagh669** [JanStas/TestyOnline#40]
Model odpowiedzialny za:
1. Pobieranie informacji z bazy danych dotyczących zarządzania grupami oraz przekazującego te dane z powrotem do kontrolera

@wlAristo

**Comment by wlAristo** [comment]
W folderze Source umieszczam plik z kodem źrodłowym.

**Comment by JanStas** [comment]
Przyjąłem ok
