### ISSUE TITLE
TESTYONLINE -039 Panel użytkownika/Zmiana danych

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#43]
Zmiana danych użytkownika - opracować funkcjonalność oraz nanieść poprawki

https://github.com/JanStas/TestyOnline/blob/Poprawki/PanelUzytkownika/Poprawki/PanelUzytkownika/Poprawki_Uzytkownik_ZmianaDanych.jpg?raw=true

**Comment by murtagh669** [comment]
Plik z kodem źródłowym został dodany. Proszę o opinie i ewentualnie o akceptacje.

**Comment by JanStas** [comment]
Poprawki wprowadzone, dziękuję bardzo zamykam taska
