### ISSUE TITLE
TESTYONLINE 42 poprawki menu administratora 

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#49]
Panel administracyjny ułożyć menu.

**Comment by JanStas** [comment]
Zmienić kolejność na

Dodaj test
Zarzadzaj testami
Zarządzaj grupami 
Wyloguj

Można zastosować styl jak w panelu użytkownika ale nie narzucam 

https://github.com/JanStas/TestyOnline/blob/master/Poprawki/PanelUzytkownika/Zrzut%20ekranu%202016-05-12%20o%2020.09.06.png

**Comment by murtagh669** [comment]
Myślę że ten styl byłby najlepszy. :)

**Comment by swagistic** [comment]
W celu odróżnienia panelu administracyjnego od panelu użytkownika styl zostanie stworzony na podobny, aczkolwiek odmienny sposób.

**Comment by wlAristo** [comment]
GUI panelu administratora zostało poprawione.
