### ISSUE TITLE
TESTYONLINE 44 - panel użytkownika 

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#51]
Podpiąć moduł rozwiązywania testów.

**Comment by wlAristo** [comment]
Prawdopodobnie w dniu dzisiejszym moduł zostanie zaprogramowany.

**Comment by wlAristo** [comment]
Funkcjonalność odpowiedzialne za przeglądanie przydzielonych do użytkownika została zaimplementowana. Trwają prace nad modułem odpowiedzialnym za rozwiązywanie testu.

**Comment by wlAristo** [comment]
Panel użytkownika został wstępnie zakończony.
