### ISSUE TITLE
TESTYONLINE 45 - Stopka

### ISSUE THREAD

**Issue by murtagh669** [JanStas/TestyOnline#52]
Proszę poprawić stopkę zgodnie ze wskazówkami.

**Comment by swagistic** [comment]
@JanStas  potrzebuję do całkowitego poprawienia stopki właściwego pliku pt. "Regulamin korzystania z serwisu" .

**Comment by wlAristo** [comment]
@JanStas Ponawiam prośbę o przygotowanie regulaminu korzystania z serwisu, bądź zlecenie realizacji tego zadania komuś innemu z zespołu.

**Comment by murtagh669** [comment]
@swagistic @wlAristo  proponuje zrobić stopke bez regulaminu. Regulamin właściwy podepniemy jak bedzie gotowy
