### ISSUE TITLE
TESTYONLINE 46 - Poprawka: komunikat podczas logowania

### ISSUE THREAD

**Issue by murtagh669** [JanStas/TestyOnline#53]
Poprawić formatowanie komunikatu podczas logowania, nie jest symetrycznie ułożony względem reszty elementów.

**Comment by swagistic** [comment]
@JanStas  czy otrzymam propozycję graficzną?

**Comment by wlAristo** [comment]
![komunikat](https://cloud.githubusercontent.com/assets/17574322/15317813/5c9af528-1c23-11e6-97dd-65d596bae014.png)

Chodzi o ten komunikat. Powinien on być sformatowany na podstawie wiadomości zwrotnej poprzez użycie klas box-default, box-error lub box-success. 

Oraz tak jak jest widoczne na zdjęciu, jest zbyt blisko niebieskiego przycisku poniżej.

**Comment by wlAristo** [comment]
Komunikat poprawiony oraz przeformatowany.
