### ISSUE TITLE
TESTYONLINE 47 - Poprawka: Panel użytkownika

### ISSUE THREAD

**Issue by murtagh669** [JanStas/TestyOnline#54]
1. We wszystkich zakładkach do których się wchodzi przenieść przycisk powrotny wyżej, a najlepiej w prawy górny narożnik.
2. ustawienia->zmiana hasla, usunąć placeholder i zrobic labelki nad polami input 
3. ustawienia->zmiana danych, to samo co wyzej, 
4. ustawienia->zmiana hasla, formatowanie komunikatu, brakuje odstepow wzgledem pól input 
5. ustawienia->zmiana danych, formatowanie komunikatu, poki co jest plain text - poprawić

**Comment by wlAristo** [comment]
Kiedy będą widoczne poprawki?

**Comment by wlAristo** [comment]
Punkt 2 poprawiony

**Comment by wlAristo** [comment]
Punkt 3 poprawiony

**Comment by wlAristo** [comment]
Punkt 4 poprawiony

**Comment by wlAristo** [comment]
Punkt 5 poprawiony
