### ISSUE TITLE
TESTYONLINE 48 - Poprawka: Panel Administratora

### ISSUE THREAD

**Issue by murtagh669** [JanStas/TestyOnline#55]
1. Panel administratora: logowanie - poprawić formatowanie pól typu input, teraz są default,
2. Poprawić: wygląd linków w panelu admina, teraz plain text jako anchor w kolorze niebieskim, zrobić tak samo jak w panelu użytkownika, (stworzenie jednej klasy css i powielanie jej w panelu admina (landing logged)) 
3. Wylogowanie powinno być w innym miejscu, może być w prawym górnym rogu bloku content owego. Ewentualnie na samym dole, poniżej wszystkimi opcjami zarządzanie grupami.
4. Poprawić formatowanie tabelki, teraz się wszystko zlewa linki typu zmień, usuń, przydziel usera można zastąpić ikonkami i podpiąć pod nie anchor kierujący przycisk dodaj nowa grupę, 
5. Dodać css admin->dodaj nowa grupe, brakuje formatowania zarówno dla inputow jak i przycisku submit formularza, oraz przycisku powrotu. 

6.NIEDOPUSZCZALNE!
 admin-> dodawanie nowego testu, tak samo styl pól typu input oraz textarea powinien zostać zmieniony, w dodatku powrót do poprzedniej strony jest gdzieś na samym dole. A tak nie może zostać! Do poprawy!
7. Przycisk powrotu powinien być zawsze w tym samym miejscu w bloku contentu osadzony jako position:absolute. Przycisk dodaj nowy test również nie ma stylu css.

**Comment by wlAristo** [comment]
1. Poprawione

**Comment by wlAristo** [comment]
Punkt 4 poprawiony

**Comment by wlAristo** [comment]
Punkt 5 poprawiony

**Comment by wlAristo** [comment]
Zmieniono: Przydziel usera ===> Przydziel osobę

**Comment by wlAristo** [comment]
Punkt 6 został poprawiony. Oformatowany został styl pól typu input oraz textarea. Przycisk powrotu został przeniesiony na góre. Callback message też jest prawidłowo już ustawiony.

**Comment by wlAristo** [comment]
Punkt 7 - Zrealizowany, w nieco inny sposób aczkolwiek jest widoczny na górze strony, na której jest użytkownik.

**Comment by wlAristo** [comment]
Punkt 3 - Wylogowanie jest widoczne na stronie głównej panelu. Zdecydowaliśmy się nie powielać tego przycisku w podstronach.

**Comment by wlAristo** [comment]
Punkt 2 - Linki zostały poprawione. Wygląda to o niebo lepiej. Mini poprawki będą sukcesywnie wdrażane w czasie dalszej pracy.
