### ISSUE TITLE
TESTYONLINE 49 - Poprawka: Panel dodawania testów

### ISSUE THREAD

**Issue by murtagh669** [JanStas/TestyOnline#56]
Najważniejsze!!!!
**Dodać** możliwość wybrania ilości pytań!*\* 
1. Podczas dodawania nowej grupy brakuje komunikatu potwierdzającego dodanie grupy bądź komunikatu o błędzie.
2. Podczas dodawania nowego testu z lewej gornej strony pojawiają się dane które trzeba usunąć
3. Podczas dodawania nowego testu brakuje komunikatu potwierdającego dodanie testu bądź komunikatu o błędzie
4. Podczas dodawania nowego testu w  przycisku  powrotu rozjechala sie ikonka strzalki
5. Podczas dodawania nowego testu glowny blok jest zakrywany przez stopke, dodać margines.

**Comment by wlAristo** [comment]
Wszystkie poprawki zostały zastosowane. Powinno wszystko ładnie śmigać. Proszę o ewentualny test i informację czy wszystko jest w porządku. Jeśli coś będzie nie tak proszę o otwarcie wątku.
