### ISSUE TITLE
TESTYONLINE 50 - Poprawka: RWD

### ISSUE THREAD

**Issue by murtagh669** [JanStas/TestyOnline#57]
Proszę poprawić RWD. Gdyż na nie wszystkich podstronach działa poprawnie.

**Comment by wlAristo** [comment]
![1024px](https://cloud.githubusercontent.com/assets/17574322/15317629/9bdf480c-1c22-11e6-88ca-391c1a3ba8c1.png)

Nadal występuje problem z poprawnym wyświetlaniem. Wklejam zrzut dla media-width 1024px
