### ISSUE TITLE
TESTYONLINE 51 - Poprawka: Rejestracja

### ISSUE THREAD

**Issue by murtagh669** [JanStas/TestyOnline#58]
1. W zarejestruj się tytuł rejestracja na gorze (pomarańczowe tło, biały napis) jest przesunięty w prawo. Powinien być przesunięty w lewo o kilka pikseli. Position:relative, left:xpx;
2. W panelu rejestracji trzeba dodać komunikat zwrotny o poprawnej rejestracji bądź błędzie który się pojawił.

**Comment by wlAristo** [comment]
Kiedy będą widoczne poprawki?

**Comment by wlAristo** [comment]
Pierwsza część została poprawiona, obrazek został przesunięty w lewo (zmiana z -10px na -20px w pos:relative;)

Komunikat zwrotny w panelu rejestracyjnym został oformatowany. Został dodany odnośnik po poprawnym założeniu konta pozwalający na przejście (anchor onClick) do panelu logowania.
