### ISSUE TITLE
TESTYONLINE 54 - Stworzenie 3 testów

### ISSUE THREAD

**Issue by wlAristo** [JanStas/TestyOnline#60]
Proszę o stworzenie trzech przykładowych testów. Proszę, aby pytania i odpowiedzi były sensy.
Proszę, aby ilość pytań w tych trzech testach wynosiła kolejno 3,4,5.

**Comment by wlAristo** [comment]
Informacja: proszę o stworzenie tych pytań nie wcześniej niż w 
Wyczyścić bazę danych #61 
pojawi się informacja o tym, że baza danych jest już gotowa.

**Comment by wlAristo** [comment]
Stworzyłem test o nazwie "znajomość języka PHP" - ilość pytań w tym teście to 5.
Proszę o utworzenie pozostałych dwóch testów @oskrz  @murtagh669  @swagistic @JanStas

**Comment by swagistic** [comment]
Test o Albanii został stworzony
