### ISSUE TITLE
TESTYONLINE 56 - Poprawki na podstawie finalnych testów

### ISSUE THREAD

**Issue by wlAristo** [JanStas/TestyOnline#62]
Poprawiony został komunikat informujący użytkownika o braku dostępnych dla niego testów.
Zrzut ekranu w załączniku.
![no_test](https://cloud.githubusercontent.com/assets/17574322/15398547/52a897f6-1de4-11e6-85d3-715e696794c1.png)

**Comment by wlAristo** [comment]
Proszę @JanStas  @oskrz  @murtagh669  @swagistic  o przejrzenie projektu w celu sprawdzenia, czy jakiś element znajdujący się na stronie nie powinien zostać poprawiony.

**Comment by wlAristo** [comment]
Została zastosowana poprawka w pliku views/testy_uzytkownika/index.php

Warunek przed zmianą: !empty($this->szczegoly_testow)
Warunek po zmianie: !empty($this->szczegoly_testow[0])

**Comment by wlAristo** [comment]
Utworzyłem nowy test
Utworzyłem nową grupę
Przypisałem do grupy test, który utworzyłem
Zalogowałem się na konto yolo@o2.pl / lol123
Podjąłem się rozwiązywania testu
Zakończyłem test
Zostałem poinformowany o moim wyniku w teście
Na stronie głównej widnieje informacja o tym jaki wynik otrzymałem. 

Informuje, że po drodze wszystko wydaje się ok.

**Comment by swagistic** [comment]
Utworzyłem nowy test na temat Albanii
Przypisałem do wcześniej utworzonej grupy test, który utworzyłem
Zalogowałem się na wcześniej stworzone konto
Podjąłem się rozwiązywania testu
Zakończyłem test
Zostałem poinformowany o moim wyniku w teście
Na stronie głównej widnieje informacja o tym jaki wynik otrzymałem.

Całość działała płynnie i nie zauważyłem błędów
