### ISSUE TITLE
TESTYONLINE 55 - Przetestowanie obecnie dostępnej funkcjonalności

### ISSUE THREAD

**Issue by wlAristo** [JanStas/TestyOnline#63]
@JanStas  @oskrz  @murtagh669  @swagistic , proszę o przetestowanie tego co mamy pod każdym możliwym kątem.

**Comment by swagistic** [comment]
Przetestowałem funkcjonalność zarówno od strony administratora jak i użytkownika. Wszystkie funkcje zdają się działać poprawnie
