### ISSUE TITLE
TESTYONLINE - 007  Baza danych

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#8]
Stworzyć model konceptualny.

**Comment by murtagh669** [comment]
Model wykonany

**Comment by JanStas** [comment]
Nanieść poprawki zgodnie z wytycznymi klienta

**Comment by murtagh669** [comment]
Poprawki zostały naniesione. Proszę o ewentualne kolejne poprawki, albo akceptacje.
