### ISSUE TITLE
TESTYONLINE - 008 Przygotowanie hostingu

### ISSUE THREAD

**Issue by JanStas** [JanStas/TestyOnline#9]
Przygotowanie miejsca na serwerze, założenie bazy danych. Przekazać dane logowania do serwera i bazy danych Marcinowi i Mateuszowi.

**Comment by swagistic** [comment]
Hosting został stworzony.
Baza została założona.
Wszystkie dane zostały przekazane.

**Comment by JanStas** [comment]
Zatwierdzam

**Comment by murtagh669** [comment]
Dane otrzymałem.
